import { App, TFile } from 'obsidian';

/**
 * WeeklySummary generates a markdown note summarizing the user's
 * vault activity for the past week.
 */
export class WeeklySummary {
    private app: App;
    private dataDir: string;

    constructor(app: App, dataDir: string) {
        this.app = app;
        this.dataDir = dataDir;
    }

    /**
     * Check if a weekly summary is due (last generated > 7 days ago).
     */
    async isDue(): Promise<boolean> {
        const lastGenerated = await this.getLastGeneratedDate();
        if (!lastGenerated) return true;

        const daysSince = (Date.now() - lastGenerated) / (1000 * 60 * 60 * 24);
        return daysSince >= 7;
    }

    /**
     * Generate the weekly summary note and save it to the vault.
     * Returns the created file, or null if generation failed.
     */
    async generate(
        folder: string,
        isPro: boolean,
        healthScore?: number,
        reviewCount?: number,
    ): Promise<TFile | null> {
        const now = new Date();
        const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

        // Gather data
        const newNotes = this.getNotesCreatedSince(weekStart);
        const modifiedNotes = this.getNotesModifiedSince(weekStart);

        // Generate markdown
        const dateStr = now.toISOString().split('T')[0]!;
        const weekStartStr = weekStart.toISOString().split('T')[0]!;
        const title = `Weekly Summary — ${dateStr}`;

        let content = `# 🧠 Vault Recall — Weekly Summary\n\n`;
        content += `**Week of ${weekStartStr} to ${dateStr}**\n\n`;
        content += `---\n\n`;

        // Activity stats
        content += `## 📊 This Week at a Glance\n\n`;
        content += `| Metric | Count |\n`;
        content += `|--------|-------|\n`;
        content += `| Notes created | ${newNotes.length} |\n`;
        content += `| Notes modified | ${modifiedNotes.length} |\n`;

        if (reviewCount !== undefined) {
            content += `| Notes reviewed | ${reviewCount} |\n`;
        }

        if (healthScore !== undefined) {
            content += `| Vault health score | ${healthScore}/100 |\n`;
        }

        content += `\n`;

        // New notes
        if (newNotes.length > 0) {
            content += `## ✨ Notes Created\n\n`;
            for (const file of newNotes.slice(0, isPro ? 50 : 10)) {
                content += `- [[${file.basename}]]`;
                if (isPro) {
                    content += ` — ${this.getSnippetSync(file)}`;
                }
                content += `\n`;
            }
            if (!isPro && newNotes.length > 10) {
                content += `- _…and ${newNotes.length - 10} more (upgrade to Pro for full list)_\n`;
            }
            content += `\n`;
        }

        // Most active notes
        if (modifiedNotes.length > 0) {
            content += `## ✏️ Most Active Notes\n\n`;
            // Sort by most recent modification
            const sorted = modifiedNotes
                .sort((a, b) => b.stat.mtime - a.stat.mtime)
                .slice(0, isPro ? 20 : 5);

            for (const file of sorted) {
                const daysAgo = Math.round((Date.now() - file.stat.mtime) / (1000 * 60 * 60 * 24));
                content += `- [[${file.basename}]] — modified ${daysAgo}d ago\n`;
            }
            content += `\n`;
        }

        // Footer
        content += `---\n\n`;
        content += `_Generated by [Vault Recall](https://vastavanjali.gumroad.com/l/nrwpa)_\n`;

        // Save the note
        try {
            // Ensure folder exists
            if (folder && !(await this.app.vault.adapter.exists(folder))) {
                await this.app.vault.createFolder(folder);
            }

            const path = folder ? `${folder}/${title}.md` : `${title}.md`;

            // Don't overwrite if already exists
            const existing = this.app.vault.getAbstractFileByPath(path);
            if (existing instanceof TFile) {
                return existing;
            }

            const file = await this.app.vault.create(path, content);
            await this.setLastGeneratedDate(Date.now());
            return file;
        } catch {
            return null;
        }
    }

    // ── Data Gathering ───────────────────────────────────────

    private getNotesCreatedSince(since: Date): TFile[] {
        return this.app.vault.getMarkdownFiles()
            .filter(f => f.stat.ctime >= since.getTime())
            .sort((a, b) => b.stat.ctime - a.stat.ctime);
    }

    private getNotesModifiedSince(since: Date): TFile[] {
        return this.app.vault.getMarkdownFiles()
            .filter(f => f.stat.mtime >= since.getTime())
            .sort((a, b) => b.stat.mtime - a.stat.mtime);
    }

    private getSnippetSync(file: TFile): string {
        const cache = this.app.metadataCache.getFileCache(file);
        if (cache?.frontmatter?.['description']) {
            return String(cache.frontmatter['description']).slice(0, 80);
        }
        return `${Math.round(file.stat.size / 1024)}KB`;
    }

    // ── Persistence ──────────────────────────────────────────

    private async getLastGeneratedDate(): Promise<number | null> {
        const path = `${this.dataDir}/weekly-summary-meta.json`;
        try {
            if (await this.app.vault.adapter.exists(path)) {
                const raw = await this.app.vault.adapter.read(path);
                const data = JSON.parse(raw);
                return data.lastGenerated ?? null;
            }
        } catch {
            // Ignore
        }
        return null;
    }

    private async setLastGeneratedDate(timestamp: number): Promise<void> {
        const path = `${this.dataDir}/weekly-summary-meta.json`;
        if (!(await this.app.vault.adapter.exists(this.dataDir))) {
            await this.app.vault.adapter.mkdir(this.dataDir);
        }
        await this.app.vault.adapter.write(path, JSON.stringify({ lastGenerated: timestamp }));
    }
}
